### ISSUE TITLE
TypeError: storage is undefined

### ISSUE THREAD

**Issue by wa0x6e** [kylecorbelli/redux-token-auth#18]
Hello,

I'm currently using the master version, as I need the `SET_HAS_VERIFICATION_BEEN_ATTEMPTED` feature. 
But there seems to be also changes in the storage handling, and I'm encountering the following error when calling the `generateAuthActions(config)` function:

    TypeError: storage is undefined

It seems that `config` is now expecting a `storage` key. As I'm using it for browser only (not native), what should I pass to `generateAuthActions(config)` in order to use localStorage as before ?

Thanks.

**Comment by michaeldawson** [comment]
I got this working by adding `storage: localStorage to the `config` hash that's passed to `generateAuthActions`.

**Comment by wa0x6e** [comment]
It's working, thank you
