### ISSUE TITLE
Logging out on refresh

### ISSUE THREAD

**Issue by bvlaar** [kylecorbelli/redux-token-auth#30]
I've integrated redux-token-auth into an application I'm building. Login and logout functionality is working well. However, it seems like experiencing some sort of race condition with regards to the `VERIFY_TOKEN_REQUEST_SENT` action. 

When I navigate to a page, the `VERIFY_TOKEN_REQUEST_SENT` action is triggered and the `reduxTokenAuth` state gets updated to `isSignedIn: false, isLoading: true`. By the time the page loads the `redirectPathIfNotSignedIn` method on my routes gets hit and it directs the user to `redirectPathIfNotSignedIn: '/',`. When I view the state on `/` after this occurs, I see the state has `isSignedIn: true, isLoading(pin): false`. 

My `app.js` code is as follows:
```
const requireSignIn = generateRequireSignInWrapper({
  redirectPathIfNotSignedIn: '/',
})

const App = () => (
  <div className='app'>
    <Router history={history}>
      <div>
        <Route exact path="/" component={LoginForm} />
        <Route path="/dashboard" component={requireSignIn(Dashboard)} />
        <Route exact path="/posts/:postId" component={requireSignIn(PostDetail)} />
      </div>
    </Router>
  </div>
);

export default App;
```

My `index.js` code:
```
const reducer = combineReducers({
  posts: posts,
  reduxTokenAuth: reduxTokenAuthReducer,
});

// create the redux store
const store = createStore(
  reducer, composeWithDevTools(
    applyMiddleware(logger),
    applyMiddleware(thunk)
  )
);

// Checks if user has existing session in localStorage
verifyCredentials(store)

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root'),
) 
```

Any help on this issue would be greatly appreciated.

**Comment by ukabthebest** [comment]
Same issue. And you are quite right. There is a race condition.

`async function demo() {
    console.log('Taking a break...');
    verifyCredentials(store);
    await sleep(3000);  
    console.log(store.getState());
    ReactDOM.render(
        <Provider store={store}>
            <Router history={hist}>
                <Switch>
                    {indexRoutes.map((prop, key) => {
                        return <Route path={prop.path} component={prop.component} key={key} />;
                    })}
                </Switch>
            </Router>
        </Provider>,
        document.getElementById("root")
    );
    console.log('Five second later');
}

demo();`


This works perfectly but is a horrible solution as server response times can vary.

**Comment by djvs** [comment]
There also appears to be an issue with devise-token-auth producing this behavior, for anyone using the two in tandem.
