### ISSUE TITLE
All the values stored in localStorage are undefined

### ISSUE THREAD

**Issue by AmitJoki** [kylecorbelli/redux-token-auth#39]
I am getting back the access tokens and everything back right from Devise Auth Token right, but when storing those into the localStorage, it is storing `undefined` and hence every other `verifyToken` is failing.

**Comment by andrewmartin** [comment]
I'm seeing the same exact issue as you. Hoping there's a solution; did you have any luck with this one? Ironically, I am working on this right now.

**Comment by AmitJoki** [comment]
@andrewmartin nope. Have been stuck with for 2 days now. I am not able to pin point which code is generating the first request. Do let me know if you've found the fix.

**Comment by AmitJoki** [comment]
Sorry my bad. There's only request, the other one being preflight request. But still, the tokens being returned correctly aren't stored in the localStorage. It is undefined. I don't know why.

**Comment by andrewmartin** [comment]
@AmitJoki 

BOOM.  I figured out what was going on after debugging and trying to write my own handler...

In my app's configuration, the headers were not being exposed. 

This is pretty critical; @kylecorbelli I might recommend adding some notes to the README (or I can open a quick PR):

```
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :delete, :put, :patch, :options, :head], :expose  => ['uid', 'client', 'expiry', 'access-token']
      end
    end
```

The important configuration here is this:
`:expose  => ['uid', 'client', 'expiry', 'access-token']`

Without this, the headers aren't actually provided to the Client in the Response; though they're visible in developer tools and such, the browser can't access them.

Hope this helps!

**Comment by AmitJoki** [comment]
@andrewmartin lots of love to you my man! The developer console did mess up. Adding that field made my app work too.

Thanks a lot! <3 Cheers :) This should definitely be on the documentation.

**Comment by andrewmartin** [comment]
The pleasure is all mine, my friend. Glad you got it spinning!

**Comment by kylecorbelli** [comment]
So happy to hear you guys got this working! This is, to be clear, an issue pertaining to configuring the Rails portion of your applications and would have been an issue whether or not `redux-token-auth` was used. Cheers!

**Comment by peterlawless** [comment]
Still having this issue, even with the rack-cors configuration.  After confirming my account via email, I am redirected to the success url and I can see access-token, client, client_id, token, expiry, etc, all in the query string parameters.  But when the client kicks off a request to verify the token, all the parameters are undefined and the request returns a 401.  It may also be worth noting that my client and server reside on the same domain?  Please help.

**Comment by AmitJoki** [comment]
I haven't gotten exactly to the bottom of the issue, but switching over to a fork of this, by joshuadev fixed my problem. Try installing hs fork of the npm package.



Sent from my Redmi 4
On Peter Lawless <notifications@github.com>, 8 May 2018 10:02 pm wrote:

Still having this issue, even with the rack-cors configuration. After confirming my account via email, I am redirected to the success url and I can see access-token, client, client_id, token, expiry, etc, all in the query string parameters. But when the client kicks off a request to verify the token, all the parameters are undefined and the request returns a 401. It may also be worth noting that my client and server reside on the same domain? Please help.
