### ISSUE TITLE
Save email to state? 

### ISSUE THREAD

**Issue by domarp-j** [kylecorbelli/redux-token-auth#40]
Would it be possible to save email in state? Looking at the docs, the `initialState` for the Redux store looks something like this: 
```
const initialState = {
  reduxTokenAuth: {
    currentUser: {
      isLoading: false,
      isSignedIn: false,
      attributes: {
        username: null, // based on what you set in your config
      },
    },
  },
};
```
And the config looks like:
```
const config = {
  authUrl: routes.signUpRoute,
  userAttributes: {
    username: 'username',
  },
  userRegistrationAttributes: {
    username: 'username',
  },
};

``` 
The docs explicitly say that email **cannot** be a part of `userAttributes` or `userRegistrationAttributes`. Since these must map `initialState.reduxTokenAuth.currentUser.attributes`, it doesn't seem possible to save email in state. 

Am I missing something, and can the email be saved in the store state?

**Comment by lrosskamp** [comment]
just add `email: 'email'` to `userAtrributes`

```
const config = {
  authUrl: routes.signUpRoute,
  userAttributes: {
    username: 'username',
    email: 'email'
  },
  userRegistrationAttributes: {
    username: 'username',
  },
};
```
worked for me..
