### ISSUE TITLE
Get undefined error after sign in and refresh page 

### ISSUE THREAD

**Issue by Qasem-h** [kylecorbelli/redux-token-auth#49]
I get this error undefined
After signing i get this message in logger: `redux-token-auth/SIGNIN_REQUEST_SUCCEEDED `
But if i refresh the page i get this error : 
`validate_token?access-token=undefined&client=undefined&uid=undefined 401 (Unauthorized)`

**Comment by imikailoby** [comment]
Reopen. I have a same issue
